---
relay:
  mode: managed
  upstream: "http://127.0.0.1:${SENTRY_PORT}/"
  host: 0.0.0.0
  port: 3333
  tls_port: ~
  tls_identity_path: ~
  tls_identity_password: ~
logging:
  level: TRACE
  enable_backtraces: true
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "127.0.0.1:9093"}
  topics:
    events: "ingest-events"
    attachments: "ingest-attachments"
    transactions: "ingest-transactions"
    outcomes: "event-outcomes"
  redis: redis://127.0.0.1:6379
