---
relay:
  mode: managed
  upstream: ${SENTRY_HOST}
  host: 0.0.0.0
  port: ${RELAY_PORT}
logging:
  level: TRACE
  enable_backtraces: true
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "127.0.0.1:9093"}
  redis: redis://127.0.0.1:6379
